"""test

Revision ID: 115adea5f1b1
Revises: 4d45770c6671
Create Date: 2016-05-20 11:58:30.241000

"""

# revision identifiers, used by Alembic.
revision = '115adea5f1b1'
down_revision = '4d45770c6671'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
