"""add body_html in Post class

Revision ID: 1d268729c805
Revises: 5a709faf7d92
Create Date: 2016-05-10 11:27:23.266000

"""

# revision identifiers, used by Alembic.
revision = '1d268729c805'
down_revision = '5a709faf7d92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
