"""add db.relationship 

Revision ID: 23b8b232bced
Revises: 392fd28114d9
Create Date: 2016-05-21 22:05:40.916000

"""

# revision identifiers, used by Alembic.
revision = '23b8b232bced'
down_revision = '392fd28114d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
