"""bug fix.

Revision ID: 2da5b0681258
Revises: 13d05e94e15b
Create Date: 2016-05-10 09:50:25.697000

"""

# revision identifiers, used by Alembic.
revision = '2da5b0681258'
down_revision = '13d05e94e15b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
