"""add body_html in Post class

Revision ID: 5a709faf7d92
Revises: 2da5b0681258
Create Date: 2016-05-10 11:25:51.141000

"""

# revision identifiers, used by Alembic.
revision = '5a709faf7d92'
down_revision = '2da5b0681258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
